### ISSUE TITLE
切换成其他语言后，会导致加载工作流时，备注的节点标题变成默认标题

### ISSUE THREAD

**Issue by Zker67** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#104]
安装此插件之后，我切换ComfyfUI语言为中文
结果导致了加载工作流时，丢失了JSON中备注的节点标题信息
当我加载一个工作流时，所有的节点会变成默认标题，而不是保存时设置的标题
当我切换回英文时，不会出现这种异常

**Comment by Yorha4D** [comment]
这不是异常，翻译的是comfyui原始名称，比如被命名为AABBCC如果不翻译原始名称节点就不知道是做什么的

**Comment by Zker67** [comment]
抱歉，我的描述不准确。
我的意思是说自己有详细命名节点的习惯，和学习他人工作流，当使用汉化插件时，会被替换成原名。
这对于比较复杂的工作流来说，使用和学习会比较不方便。
比如有两个采样器节点，一个是底模，一个是 refiner，我会对其标题都添加后缀说明。
但使用插件后加载导出的工作流，会变回原名。
