### ISSUE TITLE
与效率节点有冲突，我发视频你看看，

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#110]
这应该时汉化引起的，中文界面下。lora数量无法修改，同时lora加载节点中将会非常多lora数量。并且这个插件有自己的颜色，在汉化下。将不会起效。希望您能把这些冲突问题修复
这个插件地址https://github.com/jags111/efficiency-nodes-comfyui

https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/131615326/64aa5f01-f7e0-4699-be9a-067b2806d84a

**Comment by Yorha4D** [comment]
@wibur0620 翻译理论上不应该导致数值的变化，我测试下看看

**Comment by wibur0620** [comment]
> 启用了一些修复补丁，请参阅

The problem still exists

https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/131615326/9ce20f79-a52a-498b-b3ac-b548e18576fc
