### ISSUE TITLE
请求插件汉化

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#114]
https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION
这个插件请求汉化。这个插件能让界面变得整洁，可以约束那些链接，让界面不在杂乱无章

**Comment by DorotaLuna** [comment]
链接发错了bro

**Comment by wibur0620** [comment]
哈哈，不好意思，我重新发https://github.com/rgthree/rgthree-comfy.git

**Comment by DorotaLuna** [comment]
翻了 #123

**Comment by wibur0620** [comment]
感谢
