### ISSUE TITLE
启用插件后，输入框的选项不能通过点击来选择了

### ISSUE THREAD

**Issue by youyegit** [AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION#12]
环境：win10, 最新版 comfyui，chrome浏览器 
            问题描述：启用插件后，输入框的选项不能通过点击来选择了（不管切换中文还是英文，都还存在问题 ）。
            比如采样器里的选择项如下—— 
            "control_after_generate": "运行后操作",
                "fixed": "固定",
                "increment": "增加",
                "decrement": "减少",
                "randomize": "随机",

**Comment by Yorha4D** [comment]
> ```
>         环境：win10, 最新版 comfyui，chrome浏览器 
>         问题描述：启用插件后，输入框的选项不能通过点击来选择了（不管切换中文还是英文，都还存在问题 ）。
>         比如采样器里的选择项如下—— 
>         "control_after_generate": "运行后操作",
>             "fixed": "固定",
>             "increment": "增加",
>             "decrement": "减少",
>             "randomize": "随机",
> ```

比如哪个节点？

**Comment by youyegit** [comment]
比如：
KSampler的“control_after_generate”选项输入框，
Load lora 的“Filter list”下拉选项

**Comment by Yorha4D** [comment]
@youyegit 久等，对于提到的选项，是枚举类型数据。但在ComfyUI里没有为这个类型的数据添加name属性，还在和作者协商，相信能解决它
![image](https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION/assets/116185401/b38c301e-b8ef-4768-9882-e948f3085e96)

**Comment by DreamLoveBetty** [comment]
同样遇到这个问题，包括comfy边栏的预览模式下拉选项也无法下拉选择，并且鼠标在工作区右键无法弹出节点菜单。删除翻译节点后恢复正常.
环境：win11, 最新更新 comfyui，EDGE DEV浏览器

**Comment by Yorha4D** [comment]
@DreamLoveBetty 有尝试最大化并刷新浏览器么

**Comment by Yorha4D** [comment]
问题已修复可以自行检查
