### ISSUE TITLE
KR translation!

### ISSUE THREAD

**Issue by gehenna3702** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#124]
I don't know why, but the poll creation failed. Too difficult. Collaborator? It doesn't work when it pops up. I don't know... I translated about 35kb more. custom node.

![2023-12-13 19 00 09](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/77250986/e740d6d4-7890-4973-b453-5d1d2a84348d)

[Menu.json](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/files/13659313/Menu.json)
[NodeCategory.json](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/files/13659314/NodeCategory.json)

**Comment by DorotaLuna** [comment]
ok

**Comment by DorotaLuna** [comment]
merged #126

**Comment by Yorha4D** [comment]
@gehenna3702 Hi, I noticed that you are working on improving Korean translation.
This is really great, here's a quick way to get things done.
As you can see, translation requires extracting words. You can directly modify some more complete translation files, such as zh cn, and change the target language to Korean
Anyway, thank you for your contribution

**Comment by gehenna3702** [comment]
Oh good idea, I will introduce it in the next translation, thank you
