### ISSUE TITLE
KR translation!!

### ISSUE THREAD

**Issue by gehenna3702** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#127]
![2023-12-15 04 56 33](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/77250986/735aff75-ca52-458e-bdea-e86e467860b1)
[ko-KR.zip](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/files/13677679/ko-KR.zip)

**Comment by DorotaLuna** [comment]
merged #129
