### ISSUE TITLE
能否添加双语选项

### ISSUE THREAD

**Issue by haygcao** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#135]
您好，这个能否添加双语选项

**Comment by Yorha4D** [comment]
@haygcao 这个不太行，双语会导致字符长度过长，有些开发者写的东西没有很好地规范UI，会出现各种问题

**Comment by DorotaLuna** [comment]
[双语分支](https://github.com/DorotaLuna/AGL-comfyui-translation-canny/tree/%E4%B8%AD%E8%8B%B1%E5%8F%8C%E8%AF%AD)

**Comment by haygcao** [comment]
> [双语分支](https://github.com/DorotaLuna/AGL-comfyui-translation-canny/tree/%E4%B8%AD%E8%8B%B1%E5%8F%8C%E8%AF%AD)

非常非常感谢
