### ISSUE TITLE
求翻译https://github.com/florestefano1975/comfyui-portrait-master

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#137]
这个插件相当于一个提示词生成插件，主要用来画肖像，其他的也没问题。它作用于CLIP文本编码器之前，通过插件上面的滑条来控制提示词。然后把提示词写入文本编码器，一个非常简单但是特别实用的插件，对于很多不会写提示词的人来说。这个插件可以做到让他精细控制画面中某些元素，而且是简简单单的通过拉动可视化的滑条来实现。恳求大佬汉化此插件，
可以参考这个作者的汉化https://github.com/ZHO-ZHO-ZHO/comfyui-portrait-master-zh-cn
我有强迫症。不愿意安装第三方插件包裹住的这个插件。所以。恳请作者汉化。谢谢

**Comment by wibur0620** [comment]
不知道在哪儿可以给作者买杯咖啡，我非常乐意给辛苦的作者买杯咖啡

**Comment by DorotaLuna** [comment]
翻了 #139
咖啡什么的就不用了，多来看看视频点点赞就可以了
[space.bilibili.com/35723238/](https://space.bilibili.com/35723238)

**Comment by wibur0620** [comment]
辣椒酱就是大佬你啊，辣椒酱的视频我都是三连的

**Comment by DorotaLuna** [comment]
> 辣椒酱就是大佬你啊，辣椒酱的视频我都是三连的

俺是辣酱小弟
