### ISSUE TITLE
I got error while starting comfyUI: [agl/register error]: [WinError 1] 函数不正确。

### ISSUE THREAD

**Issue by RainRainC** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#144]
I got error while starting comfyUI: [agl/register error]: [WinError 1] 函数不正确。
And this cannot be loaded sucessfully.
Can anyone help on this?

**Comment by xieshiyu9527** [comment]
@作者大佬，我也遇到这个BUG了，系统是Win10专业版 22H2。

查看之前已经关闭的issue，找到了临时性的解决办法：将 **ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION** 目录中的内容复制一份到 **ComfyUI/web/extensions/AIGODLIKE-COMFYUI-TRANSLATION** 目录下。

但是无法一劳永逸，每次一重启ComfyUI，复制到 **ComfyUI/web/extensions/AIGODLIKE-COMFYUI-TRANSLATION** 目录下内容就被删除了！


```
 if os.name == "nt":  # Windows
     import _winapi
     _winapi.CreateJunction(CUR_PATH.as_posix(), aigodlike_ext_path.as_posix())  # [agl/register error]: [WinError 1] 函数不正确。
  else:  # Linux
      # 复制时过滤 .git
      shutil.copytree(CUR_PATH.as_posix(), aigodlike_ext_path.as_posix(), ignore=shutil.ignore_patterns(".git"))
```
有考虑将Windows平台上相关代码中的 `_winapi.CreateJunction`  去掉，统一使用 `shutil.copytree` 复制文件形式吗？

我看不少人有提到过这个BUG，但是后续一直没有解决，是因为需要兼容Windows的其它平台必须使用 `_winapi.CreateJunction` 创建连接的形式，还是别的什么原因呢？

**Comment by KarryCharon** [comment]
新版已经不需要copy文件了, 现在应该可以正常使用了
