### ISSUE TITLE
error saving setting 'AGL.Locale'

### ISSUE THREAD

**Issue by lilyzlt** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#145]
recently I  got this error

**Comment by GalileoFe** [comment]
FETCH DATA from: /home/moeblack/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
same

**Comment by GalileoFe** [comment]
same

**Comment by Yorha4D** [comment]
@KarryCharon

**Comment by soulteary** [comment]
it's very easy, try https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/pull/151

**Comment by KarryCharon** [comment]
@soulteary Merged
