### ISSUE TITLE
I can not switch language

### ISSUE THREAD

**Issue by Walson23** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#147]
在中文界面点击 切换语言 可以正常切换英文，但在英文界面点击 Switch Locale没反应，不能正常切换，重装后也没用

**Comment by Maslino** [comment]
> 在中文界面点击 切换语言 可以正常切换英文，但在英文界面点击 Switch Locale没反应，不能正常切换，重装后也没用

Hi, how do you solve this problem? I cannot switch locale too when the ui is english
