### ISSUE TITLE
系统找不到指定的文件。: 'f:\\GitHub\\ComfyUI\\web\\extensions\\AIGODLIKE-COMFYUI-TRANSLATION'

### ISSUE THREAD

**Issue by LittleTuz** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#148]
系统找不到指定的文件。: 'f:\\GitHub\\ComfyUI\\web\\extensions\\AIGODLIKE-COMFYUI-TRANSLATION'

**Comment by Fieons** [comment]
我在custom_nodes\AIGODLIKE-ComfyUI-Translation\__init__.py 将第102、103、104行添加注释就可以了：
```
#if Path(path.resolve()).as_posix() != path.as_posix():
#        path.unlink()
#        return
应该可以用try...except解决，有空可以看看。

**Comment by KarryCharon** [comment]
新版comfyui 会注册当前插件为 extension 子级, 应该不会出先这个问题了
