### ISSUE TITLE
可以帮这个节点汉化一下吗？

### ISSUE THREAD

**Issue by fs920105** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#150]
https://github.com/jafshare/ComfyUI-Easy-Tools.git
很不错的节点，GPT提示词，很简单的一句话生成的效果就很好。
一个红色连衣裙女孩走在夜间小路！
![2334838](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/135109872/afe0356b-4986-4fe2-a6f7-712d2899a9f3)

**Comment by DorotaLuna** [comment]
翻了 #152

**Comment by fs920105** [comment]
> 翻了 #152

万分感谢🙏
