### ISSUE TITLE
KR translation!

### ISSUE THREAD

**Issue by gehenna3702** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#159]
![2024-01-23 04 05 44](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/77250986/b47b871e-2314-4298-8ecf-44be041c60a5)
![2024-01-23 04 05 12](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/77250986/729ac269-935d-4fb3-a41d-93f82cb5a0f7)
[ko-KR.zip](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/files/14014446/ko-KR.zip)

**Comment by DorotaLuna** [comment]
merged #160 
bro I think you update it with pulling a request
