### ISSUE TITLE
开启中文后，ComfyUI-Manager插件管理器编译失败

### ISSUE THREAD

**Issue by liaosu0755** [AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION#17]
报告一个“BUG”，开启中文后，ComfyUI-Manager插件管理器没有翻译，而且会编译失败，特征是点插件管理器的Install Custom Nodes后，后台提示：  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 330, in get_data
    json_text = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 6223: illegal multibyte sequence
更新插件管理器、更新翻译插件、重启软件，都无法恢复插件管理器的功能

**Comment by Yorha4D** [comment]
刚又更新了一版，再试试

**Comment by liaosu0755** [comment]
> 刚又更新了一版，再试试

问题已解决，任意切换都可以了

**Comment by Yorha4D** [comment]
好的
