### ISSUE TITLE
滑条上的数值都不能显示

### ISSUE THREAD

**Issue by laidingq** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#171]
![QQ截图20240226155835](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/135723102/47158db0-5969-45dc-917d-f75f5a0e9d2c)

安装翻译插件后,无论是中文还是英文模式下，所有带滑条的节点，滑条上的数值都不能显示，移除插件后可以正常显示
更换过几款浏览器，都是同一情况

![QQ截图20240226155725](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/135723102/b4600efb-8bec-48ac-8c61-4df80a5bdd06)

**Comment by KarryCharon** [comment]
@laidingq 并没有测试到有这个问题
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/49889381/1024a370-2d1c-46fa-a554-db3bab269a02)
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/49889381/56a092fb-14a5-4ad6-a3c2-1c54aa183306)

**Comment by KarryCharon** [comment]
@laidingq 你测试一下最新版 看看是不是一样有这个问题

**Comment by laidingq** [comment]
@KarryCharon 刚重新装了 还是这个问题，我没有用装楼上的这个插件，就用的comfy默认的界面

**Comment by KarryCharon** [comment]
> @KarryCharon 刚重新装了 还是这个问题，我没有用装楼上的这个插件，就用的comfy默认的界面

你测的哪个节点, 把你的工作流发上来

**Comment by laidingq** [comment]
![workflow (1)](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/135723102/be2cf7a3-0af4-4829-afdd-c57cac7e8b6b)
图片带工作流

**Comment by KarryCharon** [comment]
@laidingq 
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/49889381/27efe4d1-6ca4-4996-b0cb-80638f808aee)
仍然没有这个问题

**Comment by KarryCharon** [comment]
@laidingq 如果方便的话 可以联系我 qq: 1016296617 到时候远程桌面 给你看看

**Comment by laidingq** [comment]
加了
