### ISSUE TITLE
【bug】远程服务器部署，中文没有生效

### ISSUE THREAD

**Issue by songispm** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#172]
我远程服务器部署，中文没有生效（本地127.0.0.1部署没这个问题），确定设置里面已经设成了中文

<img width="1896" alt="image" src="https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/38745323/26bd465f-16d5-4862-9e4d-82f65fa67236">

当 get_translation接口 晚于 object_info 接口回来的时候，中文没有生效

是因为两个接口是异步的吧？看下是不是这个原因？

**Comment by songispm** [comment]
如果解决不了异步问题，看能不能想办法尽可能的提早get_translation访问的时机

或者想办法把get_translation的结果进行localStorage缓存

**Comment by Layer-norm** [comment]
把main.js里的默认改成中文试试。如果部分插件翻译不完整就把ext常量里init(app)的async删掉。你可以参考一下我自用的版本[main.js](https://github.com/Layer-norm/AIGODLIKE-ComfyUI-Translation/blob/main/web/main.js)

**Comment by Yorha4D** [comment]
@Layer-norm 俺们研究下

**Comment by songispm** [comment]
> 把main.js里的默认改成中文试试。如果部分插件翻译不完整就把ext常量里init(app)的async删掉。你可以参考一下我自用的版本[main.js](https://github.com/Layer-norm/AIGODLIKE-ComfyUI-Translation/blob/main/web/main.js)

用了你的仓库的版本，依然没能解决问题

**Comment by KarryCharon** [comment]
@songispm 已修复, 你测测看

**Comment by songispm** [comment]
> @songispm 已修复, 你测测看

测试有效，请求异步变成了同步，赞

**Comment by KarryCharon** [comment]
> @KarryCharon 但是还有另一个小问题就是，已经在setting中被设置中文，但当第一次加载的时候（也就是localStorage中这一条还没有的时候），中文没有生效，再刷一次就生效了（下一次刷新的时候localStorage中就有了 zh-CN）
> 
> <img alt="image" width="998" src="https://private-user-images.githubusercontent.com/38745323/309560161-3dfecec4-4baf-4777-ac1d-69aa491f7ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDg4MzAsIm5iZiI6MTcwOTUwODUzMCwicGF0aCI6Ii8zODc0NTMyMy8zMDk1NjAxNjEtM2RmZWNlYzQtNGJhZi00Nzc3LWFjMWQtNjlhYTQ5MWY3ZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDIzMjg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NGJhMWZlMWMwZjBjZThhMmE5NGUyZWJjNzE0Nzk2ZGM1MWM2ZDRkN2NiNTZlN2YxYjZkZjgxYTQyMTUxYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d8dwH-wKVhQ7cHb8io1ADFeCTjKWpMZ7eSB7tKss6Sc">
> 如何测试呢，就是你把AGL.Locale这条localStorage清掉就复现了
> 
> 当然是属于另一个问题了，可以慢慢再解

这个也修复了
@songispm 你试试
