### ISSUE TITLE
有兴趣把这个插件翻了吗

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#176]
https://github.com/gokayfem/ComfyUI_VLM_nodes

**Comment by wibur0620** [comment]
还有这个https://github.com/cubiq/ComfyUI_essentials

**Comment by DorotaLuna** [comment]
> 还有这个https://github.com/cubiq/ComfyUI_essentials

#177

**Comment by DorotaLuna** [comment]
> https://github.com/gokayfem/ComfyUI_VLM_nodes

#178
