### ISSUE TITLE
Custom-Scripts相关，原文本中的符号及字母大小写问题

### ISSUE THREAD

**Issue by rogerism** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#179]
![en](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/9543573/30980406-4b3a-4e84-8cf8-918fb512ceda)
![cn](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/9543573/364a4080-63e5-40e1-837b-4b3ade24cdc3)

[ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)插件产生的选项和节点标题原文是带有符号的，不知为何汉化后被移除。另外比较重要的一点是，这个表达式节点的输入项原文是小写字母，汉化后变成了大写字母，但实际上节点仅支持小写字母作输入变量名，在使用中产生了误导，不知能否修正。

![图片](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/9543573/88b43e0b-9caf-41fd-aab8-ab7e7f4f81d2)
![图片](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/9543573/6d98d105-34fb-432e-a91a-02aa084e89a1)
另外，同插件所增加的自定义颜色功能在中文下也消失，不知是否与前面的表情符号有关。

**Comment by DorotaLuna** [comment]
大小写的问题改了#180 
自定义颜色是因为这是custom-scripts作者自己定义的功能，所以插件读不到这个东西

**Comment by rogerism** [comment]
> 大小写的问题改了#180 自定义颜色是因为这是custom-scripts作者自己定义的功能，所以插件读不到这个东西

感谢跟进，希望未来有机会都能解决
