### ISSUE TITLE
ComfyUI-Lora-Auto-Trigger-Words这个lora触发词自动从C站获取的插件有兴趣汉化吗？

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#198]
[ComfyUI-Lora-Auto-Trigger-Words](https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words)插件能自动从C站获取lora的触发词。并加入工作流中。

**Comment by wibur0620** [comment]
搞错了，有更好的这种类型的插件，https://github.com/Extraltodeus/LoadLoraWithTags

**Comment by DorotaLuna** [comment]
#199 
俩都翻了

**Comment by wibur0620** [comment]
> #199 俩都翻了

太给力啦
