### ISSUE TITLE
控件上点击鼠标右键，在弹出的菜单里 的“Convert input to ”，点击无效

### ISSUE THREAD

**Issue by TFL-TFL** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#201]
安装节点后，使用2024.4.13 （58812ab）版本的ComfyUI，点击 “Convert input to ” 无效。
在不使用节点的情况下是正常的
![Snipaste_2024-04-13_15-37-51](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/63155358/7a3a6c45-092b-4637-b104-e26a20c86171)

**Comment by niyuanfa** [comment]
我也碰到了

**Comment by liulsg** [comment]
Same problem (tested, node translation conflicts with latest comfyui version)

**Comment by escalate007** [comment]
the same here

**Comment by samen168** [comment]
Mark, the same question

**Comment by bosima** [comment]
可以暂时回退ComfyUI到旧版本 git checkout 4bd7d55b9028d79829a645edfe8259f7b7a049c0

**Comment by lzhfdwu007** [comment]
是和COMFYUI的本身冲突了。。新版本COMFYUI加了个类似的功能。。。希望作者可以早点修复吧
Keywords: Convert To Input

Issue News:

[Conver To Input] The AIGODLIKE-ComfyUI-Translation is causing conflicts with the Convert To Input feature of the latest ComfyUI update.
Feature News:
*

ComfyUI: 2127[744ac9](2024-04-13)
Manager: V2.17

**Comment by K-O-N-B** [comment]
希望早日修复

**Comment by aqidesign** [comment]
Same problem

**Comment by koilu** [comment]
mark

**Comment by silingyuan0** [comment]
遇到问题

**Comment by hzz219** [comment]
加一

**Comment by nirenyang** [comment]
+1

**Comment by migao12** [comment]
可以先用 4/12 頂著用。 
4bd7d55b9028d79829a645edfe8259f7b7a049c0

下載解壓把 widgetInputs.js 替換掉新版的就可以了。

路徑如下：
ComfyUI-4bd7d55b9028d79829a645edfe8259f7b7a049c0\web\extensions\core\ widgetInputs.js

**Comment by KarryCharon** [comment]
@TFL-TFL @niyuanfa @nirenyang @migao12 @hzz219 @silingyuan0 @koilu @K-O-N-B @koilu @aqidesign @lzhfdwu007 @samen168 @escalate007 @liulsg Fixed now. Try the newest version. 已经修复, 可以试试最新的版本

**Comment by taod518** [comment]
感谢，已经修复了！更新一下

**Comment by Swmailv** [comment]
> @TFL-TFL @niyuanfa @nirenyang @migao12 @hzz219 @silingyuan0 @koilu @K-O-N-B @koilu @aqidesign @lzhfdwu007 @samen168 @escalate007 @liulsg Fixed now. Try the newest version. 已经修复, 可以试试最新的版本

升级了最新还是没有解决

**Comment by TFL-TFL** [comment]
> @TFL-TFL @niyuanfa @nirenyang @migao12 @hzz219 @silingyuan0 @koilu @K-O-N-B @koilu @aqidesign @lzhfdwu007 @samen168 @escalate007 @liulsg Fixed now. Try the newest version. 已经修复, 可以试试最新的版本
辛苦了，现在已经正常了

**Comment by TFL-TFL** [comment]
> @TFL-TFL @niyuanfa @nirenyang @migao12 @hzz219 @silingyuan0 @koilu @K-O-N-B @koilu @aqidesign @lzhfdwu007 @samen168 @escalate007 @liulsg Fixed now. Try the newest version. 已经修复, 可以试试最新的版本

非常感谢，现在已经正常了

**Comment by Swmailv** [comment]
> 你是怎么升级的呢？

在软件里的管理器升级的

**Comment by Swmailv** [comment]
> > > 你是怎么升级的呢？
> > 
> > 
> > 在软件里的管理器升级的
> 
> 从这里下载吧先, 其他人都说修复了
已解决谢谢

**Comment by lzhfdwu007** [comment]
我自己在COMFYUI MANAGER里也是检测不到最新版本

但是到AIGODLIKE-COMFYUI-TRANSLATION目录下运行一次git pull就成功升级到最新版并且修复了这个BUG了，谢谢作者



&nbsp;


eis
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月18日(星期四) 晚上6:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AIGODLIKE/AIGODLIKE-ComfyUI-Translation] 控件上点击鼠标右键，在弹出的菜单里 的“Convert input to ”，点击无效 (Issue #201)














    
你是怎么升级的呢？
  
在软件里的管理器升级的
  
从这里下载吧先, 其他人都说修复了
 已解决谢谢

**Comment by escalate007** [comment]
感谢😀

**Comment by flyricci** [comment]
我管理器升级到最新没用，于是我直接下载最新的AIGODLIKE插件覆盖上去就解决了

**Comment by lalianer** [comment]
> 我自己在COMFYUI MANAGER里也是检测不到最新版本 但是到AIGODLIKE-COMFYUI-TRANSLATION目录下运行一次git pull就成功升级到最新版并且修复了这个BUG了，谢谢作者 &nbsp; eis ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月18日(星期四) 晚上6:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [AIGODLIKE/AIGODLIKE-ComfyUI-Translation] 控件上点击鼠标右键，在弹出的菜单里 的“Convert input to ”，点击无效 (Issue #201) 你是怎么升级的呢？ 在软件里的管理器升级的 从这里下载吧先, 其他人都说修复了 已解决谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

感谢 问题解决了！
