### ISSUE TITLE
The AIGODLIKE-ComfyUI-Translation is causing conflicts with the Convert To Input feature of the latest ComfyUI update.

### ISSUE THREAD

**Issue by JackyMee32** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#204]
Keywords: Convert To Input

Issue News:

[Conver To Input] The AIGODLIKE-ComfyUI-Translation is causing conflicts with the Convert To Input feature of the latest ComfyUI update.
<img width="1044" alt="image" src="https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/42921911/fd5ca9e3-cf79-42e8-9cff-4b45712114b7">
<img width="763" alt="image" src="https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/42921911/c8bc6483-e320-491d-ad36-50264a9e414e">

**Comment by bosima** [comment]
roll back ComfyUI to an older version:

git checkout 4bd7d55b9028d79829a645edfe8259f7b7a049c0

**Comment by wongpor** [comment]
same issue, disable this custom node for now, until they fix it

**Comment by KarryCharon** [comment]
@bosima @JackyMee32 Fixed. Try the newest version
