### ISSUE TITLE
rgthree（RG节点）部分节点在中文状态下无法加载

### ISSUE THREAD

**Issue by henji-henji** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#209]
rgthree（RG节点）部分节点在中文状态下无法加载，但是切换到英文就正常了
_删除 AIGODLIKE-COMFYUI-TRANSLATION\zh-CN\Nodes 下的 rgthree-comfy.json 也可以暂时解决问题_
比如说 rgthree 的 Reroute（转接点）

<img width="423" alt="PixPin_2024-04-18_01-19-37" src="https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/84775360/a27badda-4982-4288-a446-eb654d3f04d4">
<img width="405" alt="PixPin_2024-04-18_01-19-56" src="https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/84775360/8f1e24e1-c86e-4704-a0c3-bfd3f15e5571">

**Comment by DorotaLuna** [comment]
这个是因为reroute节点没按照comfyui的正常格式来写，翻译插件替换了名称之后他自己就找不到节点了
下次翻译更新把reroute和node collector删了就正常了但是没法翻译，我们要适配的话要改很多东西

**Comment by henji-henji** [comment]
> 这个是因为reroute节点没按照comfyui的正常格式来写，翻译插件替换了名称之后他自己就找不到节点了 下次翻译更新把reroute和node collector删了就正常了但是没法翻译，我们要适配的话要改很多东西

原来如此，感谢解答
