### ISSUE TITLE
有兴趣汉化这几个插件吗

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#213]
1：提示词管理工具
https://github.com/florestefano1975/comfyui-prompt-composer
2：面部相似度评分
 https://github.com/cubiq/ComfyUI_FaceAnalysis
3： inpainting 工具的 ComfyUI 节点集合，包括 Fooocus inpaint 模型、LaMa、MAT 等各种工具用于预先填充 inpaint 和 outpaint 区域。
  https://github.com/Acly/comfyui-inpaint-nodes
4：一个快速对视频进行抠图和制作绿幕的插件
https://github.com/Fannovel16/ComfyUI-Video-Matting
5：自动缩放 CFG / 防烧伤版本，提供 30% 的速度提升。
https://github.com/Extraltodeus/ComfyUI-AutomaticCFG
6：细节修复插件，增强图像细节和放大，目前应该算是最好的图像修复技术，
https://github.com/kijai/ComfyUI-SUPIR
7：和6号同一个作者的放大插件。
https://github.com/kijai/ComfyUI-CCSR
8：采用语言模型实现本地翻译
https://github.com/AIGCTeam/ComfyUI_kkTranslator_nodes
3：DynamiCrafter 插件是用于动画开放域静态图像，基于文本提示和预训练视频扩散先验。该项目支持生成高达 16 帧的视频
https://github.com/ExponentialML/ComfyUI_Native_DynamiCrafter?tab=readme-ov-file

**Comment by DorotaLuna** [comment]
💢怎么这么多
今天先翻俩，#215

- [x] comfyui-prompt-composer
- [x] ComfyUI_FaceAnalysis
- [ ] comfyui-inpaint-nodes
- [ ] ComfyUI-Video-Matting
- [ ] ComfyUI-AutomaticCFG
- [ ] ComfyUI-SUPIR
- [ ] ComfyUI-CCSR
- [ ] ComfyUI_kkTranslator_nodes
- [ ] ComfyUI_Native_DynamiCrafter

**Comment by wibur0620** [comment]
有点不好意思，就是上面发给你的ComfyUI_Native_DynamiCrafter这个插件，问题很多，有一个作者写的更好，https://github.com/kijai/ComfyUI-DynamiCrafterWrapper
如果你没还没翻译ComfyUI_Native_DynamiCrafter这个，可以跳过他，翻译我链接中的这个，谢谢

**Comment by DorotaLuna** [comment]
#218 
- [x] comfyui-prompt-composer
- [x] ComfyUI_FaceAnalysis
- [x] comfyui-inpaint-nodes
- [x] ComfyUI-Video-Matting
- [x] ComfyUI-AutomaticCFG
- [ ] ComfyUI-SUPIR
- [ ] ComfyUI-CCSR
- [ ] ComfyUI_kkTranslator_nodes
- [ ] ComfyUI_Native_DynamiCrafter
- [ ] ComfyUI-DynamiCrafterWrapper

**Comment by DorotaLuna** [comment]
#220 #219
- [x] comfyui-prompt-composer
- [x] ComfyUI_FaceAnalysis
- [x] comfyui-inpaint-nodes
- [x] ComfyUI-Video-Matting
- [x] ComfyUI-AutomaticCFG
- [x] ComfyUI-SUPIR
- [x] ComfyUI-CCSR
- [x] ComfyUI_kkTranslator_nodes
- [x] ComfyUI_Native_DynamiCrafter
- [x] ComfyUI-DynamiCrafterWrapper
