### ISSUE TITLE
Convert Widget to Input无法翻译，不知道哪里有问题？

### ISSUE THREAD

**Issue by zesenzhang** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#217]
你好， 我的comfyUI菜单中的 “Convert Widget to Input“模块无法翻译，不知道是哪里出现问题了，有什么方法可以修复吗？
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/31401503/ff74b2fb-255f-4402-be8c-400fa930cc5c)

**Comment by DorotaLuna** [comment]
因为本体这里的名字一直在改，现在翻译里的是`Convert widget to input`

**Comment by DorotaLuna** [comment]
更新了 #218

**Comment by zesenzhang** [comment]
好的 非常感谢
