### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by hahajaja** [AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION#22]
pipe应该翻译成管线,unclip翻译成逆clip太出戏了建议保持原样

**Comment by Yorha4D** [comment]
已收到，我去和负责汉译英的朋友讨论下 @hahajaja

**Comment by Yorha4D** [comment]
@hahajaja 久等，今天当面切磋了下，确认将修改为UNCLIP，感谢建议
