### ISSUE TITLE
给推介个非常不错的插件

### ISSUE THREAD

**Issue by wibur0620** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#225]
ComfyUI-IF_AI_tools插件
https://github.com/if-ai/ComfyUI-IF_AI_tools
作用是灵活使用各种大预言模型在comfyui进行图像跟提示词相关的操作（比如反推图像，自动润色提示词）之所以可以灵活使用各种大模型。是因为此插件把ollama作为大语言模型运行的后端，所以只要是ollama能支持的模型。此插件都能完美支持，

这个插件推荐给汉化组的各位。

**Comment by DorotaLuna** [comment]
#228 翻了
