### ISSUE TITLE
又是老问题，几个中文翻译又不行了，哈哈哈

### ISSUE THREAD

**Issue by zesenzhang** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#227]
他们又改了命名吗？真不知道为什么老是改这些小东西，。。。。
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/31401503/eab5f561-07ba-4916-a38d-2c6e584e2d14)

**Comment by zesenzhang** [comment]
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/31401503/970bedbd-06a2-409d-8b85-9a68146409f5)

**Comment by zesenzhang** [comment]
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/31401503/ac8bbe13-70be-43e4-aefd-5390bc52adb5)

**Comment by zesenzhang** [comment]
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/31401503/da8a833a-3315-4e13-b3f7-3a122fd5d662)
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/31401503/b65b3d79-a11b-4392-a3fe-b6de08b9fbaf)

**Comment by DorotaLuna** [comment]
我这里没遇到没翻译的情况，更新一下翻译看看
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/122320001/29574b2c-376b-4e58-849f-d6adc21f06f4)
