### ISSUE TITLE
请问comfyui核心节点的翻译文件是哪个？

### ISSUE THREAD

**Issue by Wangqj31** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#229]
我在测试时看到，在自定义节点中如果需要保留某个模块的自定义标题，只要删除该节点模块中"title"字段就可以使用自定义的标题（不被翻译），现在我想保留核心节点中的“加载图像”的标题不被翻译，想请问这个节点名在哪一个文件中，我试着在所有.json文件中没有找到。谢谢！

**Comment by DorotaLuna** [comment]
zh-CN/Nodes/internal.json

**Comment by Wangqj31** [comment]
已解决，非常感谢！

> zh-CN/节点/internal.json
