### ISSUE TITLE
Portrai Master应该是更新了，当前的翻译不完整，有更新的计划？

### ISSUE THREAD

**Issue by gooyoyo** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#231]
Portrai Master应该是更新了，当前的翻译不完整，有更新的计划？
https://github.com/florestefano1975/comfyui-portrait-master

**Comment by DorotaLuna** [comment]
#232 更新了一些翻译
发型类的没有翻，
在中文互联网上稍微翻了一下，发现有相当多关于发型的词没法一一对应，我没了解过这个领域所以也不知道专业的名称叫什么
即使加上翻译也可能完全看不懂这个词对应什么发型，所以就先放着不管了
