### ISSUE TITLE
Your node is changing my users workflow for no reason!

### ISSUE THREAD

**Issue by NimaNzrii** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#244]
### Issue with Input Name in "Anything Everywhere" Node workflows

I'm the developer of [comfyui-photoshop](https://github.com/NimaNzrii/comfyui-photoshop) and I'm using the "Anything Everywhere" node in my workflow. This node is crucial for me.

The problem I'm facing is that I need to change the names of some inputs, but your node keeps reverting the input names back to the original, causing significant issues with "Anything Everywhere" connections.

**Comment by KarryCharon** [comment]
> if its possible just tell me how long does it takes to fix it or maybe disable it .

Can you give me a simple workflow for testing?
