### ISSUE TITLE
使用翻译以后颜色选项少了自定义这个。

### ISSUE THREAD

**Issue by msola-ht** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#251]
![PixPin_2024-07-05_09-52-43](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/45963567/09a57803-3b1d-4ace-a9e3-46c8b2954849)
![PixPin_2024-07-05_09-53-09](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/45963567/be79271e-439d-4a9e-baf7-4727af1327ec)

英文版本有自定义，用中文版本就没了，请问这个是翻译问题还是其他插件相关

**Comment by BannyLon** [comment]
请问这个问题你解决了吗？

**Comment by Pythonpa** [comment]
the same,+1,

**Comment by KarryCharon** [comment]
Fixed: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/300
