### ISSUE TITLE
Apply for plugin translation: ComfyUI-3D-MeshTool

### ISSUE THREAD

**Issue by 807502278** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#252]
address：
https://github.com/807502278/ComfyUI-3D-MeshTool

I'm testing locally and I don't know why it didn't work,There are no any error reports either.  
[ComfyUI-3D-MeshTool.json](https://github.com/user-attachments/files/16122975/ComfyUI-3D-MeshTool.json)

**Comment by DorotaLuna** [comment]
3 issue
trailing comma, 
\- and _ problem, 
few translation errors

all fix and merged #261, you can edit or add translation by pr

**Comment by 807502278** [comment]
Thank you very much.
