### ISSUE TITLE
使用翻译插件汉化后ComfyUI-Custom-Scripts插件中的颜色功能自定义缺失

### ISSUE THREAD

**Issue by BannyLon** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#254]
大家好，请教个问题，在使用这个插件汉化后，ComfyUI-Custom-Scripts插件中的Custom Colors缺少自定义颜色的功能，切换到英文后就一切正常。如下图：
![1721376470214](https://github.com/user-attachments/assets/d41462dc-47ef-4036-81d6-ddd9a5a714cc)

**Comment by Pythonpa** [comment]
The same,+1

**Comment by BannyLon** [comment]
大佬也不出来解释下造成这个错误的原因，知道原因后大家可以一起研究，毕竟众人拾柴火焰高吗？求插件作者看见回复。。。。这样的话我们可以共同参与寻找解决办法。

**Comment by KarryCharon** [comment]
> 大佬也不出来解释下造成这个错误的原因，知道原因后大家可以一起研究，毕竟众人拾柴火焰高吗？求插件作者看见回复。。。。这样的话我们可以共同参与寻找解决办法。

Fixed: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/300

**Comment by KarryCharon** [comment]
> 大佬也不出来解释下造成这个错误的原因，知道原因后大家可以一起研究，毕竟众人拾柴火焰高吗？求插件作者看见回复。。。。这样的话我们可以共同参与寻找解决办法。

这个是他插件自己的逻辑导致的, 和汉化无关

**Comment by Pythonpa** [comment]
> > 大佬也不出来解释下造成这个错误的原因，知道原因后大家可以一起研究，毕竟众人拾柴火焰高吗？求插件作者看见回复。。。。这样的话我们可以共同参与寻找解决办法。
> 
> 这个是他插件自己的逻辑导致的, 和汉化无关

666,还是同样感谢大佬。
我感觉现在缺一套基于ComfyUI的节点开发统一规范，需要有个能人振臂一呼，全球都按一定基本规范来开发节点，lol

**Comment by BannyLon** [comment]
> > 大佬也不出来解释下造成这个错误的原因，知道原因后大家可以一起研究，毕竟众人拾柴火焰高吗？求插件作者看见回复。。。。这样的话我们可以共同参与寻找解决办法。
> 
> 这个是他插件自己的逻辑导致的, 和汉化无关

感谢大佬。
