### ISSUE TITLE
ComfyUI-AdvancedLivePortrait，表情控制插件

### ISSUE THREAD

**Issue by abmmmm** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#260]
[ComfyUI-AdvancedLivePortrait.json](https://github.com/user-attachments/files/16504407/ComfyUI-AdvancedLivePortrait.json)
我自己动手把测试过的一些功能翻译了，其他没确定的功能没翻译，大家有兴趣的，可以接着翻译

**Comment by DorotaLuna** [comment]
翻了#261，
改了一点翻译，适配整个翻译的用语习惯，
要是觉得改的不好可以pr
