### ISSUE TITLE
Double-click to open the search node delay

### ISSUE THREAD

**Issue by johnchrisboys** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#277]
So far so good, but there is one problem with the new version
Starting with version #270, a double-click open delay ensued, and the input box seemed to close itself when searching for input nodes.
Today, I tried updating the latest version #276 and the problem persists with the double-click open delay!

**Comment by huchenlei** [comment]
Should be fixed by https://github.com/Comfy-Org/ComfyUI_frontend/pull/713.

Make sure you use the latest frontend release follow instruction in https://github.com/Comfy-Org/ComfyUI_frontend#nightly-release
