### ISSUE TITLE
现在新版还会有reset node名字的问题吗？

### ISSUE THREAD

**Issue by K-O-N-B** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#280]
3个月前这个bug还在，就是我重新命名了node的输入和输出端，但是只要把comfyui从中文变成英文，然后再变回中文，那些我改过名的输入输出端，就会被reset成为默认的名字

比如我把node里面的“image” 改成 ”第一张图片”
经过语言更替后，会就重置成为“image”

**Comment by Yorha4D** [comment]
@K-O-N-B 能修早就修了，这是comfyui的问题，代码也递交了，只有comfyui合并了代码或者加入了新源码这个功能才能实现

**Comment by K-O-N-B** [comment]
> 请问，这个问题如何解决？

用英文版界面，放弃中文翻译插件
