### ISSUE TITLE
Apply for plugin translation

### ISSUE THREAD

**Issue by water110** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#286]
https://github.com/kijai/ComfyUI-segment-anything-2
https://github.com/kijai/ComfyUI-Florence2
https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch

**Comment by DorotaLuna** [comment]
#288

**Comment by DorotaLuna** [comment]
> > #288
> 
> Does this mean it’s finished?

Yep, beacause this repo's active translator is zh-CN user, so basically every extension request is requesting for zh-CN translation, even they asking in other language (idk why but that is).
If you are asking for other language translation, you can reopen this issue then wait translators.
