### ISSUE TITLE
Can't find the AGL menu in the settings

### ISSUE THREAD

**Issue by Morty503** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#298]
I tried all the installation methods and confirmed that the installation has been installed, but the AGL menu cannot be found in the settings

**Comment by rp0213** [comment]
Mine can't find AGL in the settings, and the settings are also in English, so you can't change other languages

**Comment by hoonkies** [comment]
Should be fixed by https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/pull/296

**Comment by hoonkies** [comment]
Please download the new *.js from https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/pull/296

**Comment by Morty503** [comment]
> Please download the new *.js from #296

It's working, thanks

**Comment by DorotaLuna** [comment]
fixed in 56496f4
