### ISSUE TITLE
Spelling Mistakes Found in JSON Files

### ISSUE THREAD

**Issue by taxi13245** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#300]
Hello,

I would like to report some spelling mistakes I found in the JSON files. This issue appears to be present in files of all languages. Here are the details:

**In Efficiency Nodes.json:**
- Incorrect: `KSampler (Efficient).widgets.treu (tiled)`  
  Correct: `KSampler (Efficient).widgets.true (tiled)`  
- Incorrect: `KSampler Adv. (Efficient).widgets.treu (tiled)`  
  Correct: `KSampler Adv. (Efficient).widgets.true (tiled)`  
- Incorrect: `KSampler SDXL (Eff.).widgets.treu (tiled)`  
  Correct: `KSampler SDXL (Eff.).widgets.true (tiled)`  
- Incorrect: `Image Overlay.widgets.Resize to width & heigth`  
  Correct: `Image Overlay.widgets.Resize to width & height`  

**In WAS_suite.json:**
- Incorrect: `Text File History Loader.ooutputs`  
  Correct: `Text File History Loader.outputs`  

I hope this helps in improving the quality of the documentation. Thank you!

**Comment by DorotaLuna** [comment]
#301 
all translations are done in manually so there often occurs mistakes
thx for notice that
