### ISSUE TITLE
设置里面汉化失效

### ISSUE THREAD

**Issue by Terminator-AGI** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#307]
设置里面切换 TAB 标签之后恢复成英文，移动 dialog 后触发事件切换回简体中文
Chrome 131.0.6778.86
macOS 15.1.1
https://github.com/user-attachments/assets/19eac388-d4a3-41e0-8e61-9565a2173720

**Comment by ieatchili2024** [comment]
> 设置里面切换 TAB 标签之后恢复成英文，移动 dialog 后触发事件切换回简体中文 Chrome 131.0.6778.86 macOS 15.1.1 https://github.com/user-attachments/assets/19eac388-d4a3-41e0-8e61-9565a2173720

我也遇到了同样的问题，切换旧版本后，问题依旧存在。

**Comment by Terminator-AGI** [comment]
ComfyUI_frontend [v1.5.10](https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.5.10) 已修复
