### ISSUE TITLE
更新到最新的版本，comfyui搜索节点时超级卡

### ISSUE THREAD

**Issue by 9l** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#310]
更新到 0ed6982f23d225dac56fb4dbd4407998cb89d056 时，comfyui搜索节点时超级卡，禁用了除本插件外的所有自定义插件，搜索节点时的卡顿还是存在。禁用本插件或 checkout 本插件到 cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a 时搜索节点的卡顿就没有了

comfyui 版本从 comfyanonymous/ComfyUI@8af9a91e0c47b9fc277077f2079873adf8edac05 到 comfyanonymous/ComfyUI@44db9785310ab6ce7214ba7f04060bdbe572d284 都卡，再早的就没试了

**Comment by chengyinqiao1976** [comment]
我的也是同样的问题，非常卡

**Comment by Zer0xPoint** [comment]
同样 有个问题：如果不用本地化的功能，是否可以卸载此插件？

**Comment by Myoko** [comment]
退回11月的 12月的暂时不要更新

**Comment by sdjkdghj123** [comment]
升级到最新版本会卡顿，希望解决下

**Comment by ouyang3333** [comment]
一样的问题，搜索节点功能几乎不可用，是否因为翻译逻辑问题，导致每次搜索触发大批量翻译任务，还是因为实时翻译所以非常卡顿，几乎严重的时候会吧整个页面卡死，希望得到解决，非常感谢

**Comment by curtis110101010** [comment]
+1

**Comment by liuweikaiphoto** [comment]
同样的问题，搜索节点功能几乎不可用，是否因为翻译逻辑问题，导致每次搜索触发大批量翻译任务，还是因为实时翻译所以非常卡顿，几乎严重的时候会把整个页面卡死，希望得到解决，非常感谢

**Comment by AiD-teng** [comment]
同样的问题，非常卡。

**Comment by wushengda** [comment]
comfyui搜索节点时超级卡，一度让我怀疑是不是我电脑出问题了，而且最近的版本中其他插件内存也占用也好高，我去加了64G内存，刚刚根据楼上的回答把版本回退到11月份的试了下，就好了.

When searching for nodes on Comfyui, it got stuck and made me suspect that there might be a problem with my computer. Additionally, other plugins in the latest version are also taking up a lot of memory, so I added 64GB of memory. I just tried rolling back the version to November based on the answer from upstairs, and it's fine now

**Comment by q7793527** [comment]
Mine is the same. I deliberately reinstalled the entire ComfyUI yesterday, but the result is still the same.

**Comment by q7793527** [comment]
It's true that it returned to normal after going back to the November version.

> 退回11月的12月的暂时不更新

**Comment by ioritree** [comment]
我還以為是我裝太多插件問題,原來是你啊...

**Comment by Winson0616** [comment]
借一个兄弟的解决方法分享给大家，在这个插件的文件夹cmd, 输入git checkout cf8f9a8，就可以解决了，就是退回之前的版本。

**Comment by zhaoxi12312** [comment]
This problem caused me very uncomfortable, affecting the mood of the day

**Comment by Yorha4D** [comment]
> 更新到 [0ed6982](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/commit/0ed6982f23d225dac56fb4dbd4407998cb89d056) 时，comfyui搜索节点时超级卡，禁用了除本插件外的所有自定义插件，搜索节点时的卡顿还是存在。禁用本插件或 checkout 本插件到 [cf8f9a8](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/commit/cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a) 时搜索节点的卡顿就没有了
> 
> comfyui 版本从 [comfyanonymous/ComfyUI@8af9a91](https://github.com/comfyanonymous/ComfyUI/commit/8af9a91e0c47b9fc277077f2079873adf8edac05) 到 [comfyanonymous/ComfyUI@44db978](https://github.com/comfyanonymous/ComfyUI/commit/44db9785310ab6ce7214ba7f04060bdbe572d284) 都卡，再早的就没试了

I will try to fix it

**Comment by CallAjax** [comment]
After updating to the latest version, I also have this issue

**Comment by flyricci** [comment]
我也一样搜索节点直接卡死，然后把搜索框改回了老版的搜索样式才正常，新版搜索不行

**Comment by yvanq1** [comment]
我也是，太卡了，怎么回退版本呀

**Comment by Yorha4D** [comment]
@9l @Myoko @Pythonpa @Zer0xPoint @CallAjax 经过沟通，我们未来将为官方的翻译功能做贡献，此工具将停止维护

**Comment by Pythonpa** [comment]
> @9l @Myoko @Pythonpa @Zer0xPoint @CallAjax 经过沟通，我们未来将为官方的翻译功能做贡献，此工具将停止维护

辛苦了你们，致敬，这个影响相对不大，且目前全英文或者回退到11月版都能解决。期待更好的作品，瑞思拜

**Comment by hben35096** [comment]
开始出现搜索卡顿的版本是12月10日开始的，也就是哈希值： 0ed6982f23d225dac56fb4dbd4407998cb89d056
大家可以回退到 12月2日，哈希值：cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a

**Comment by flyricci** [comment]
> 借一个兄弟的解决方法分享给大家，在这个插件的文件夹cmd, 输入git checkout [cf8f9a8](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/commit/cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a)，就可以解决了，就是退回之前的版本。

这个有用

**Comment by Myoko** [comment]
> @9l @Myoko @Pythonpa @Zer0xPoint @CallAjax 经过沟通，我们未来将为官方的翻译功能做贡献，此工具将停止维护

这个工具挺好用！这个问题影响不大，感谢你们为此所做的贡献

**Comment by KarryCharon** [comment]
@9l @Myoko @Pythonpa @Zer0xPoint @CallAjax @flyricci @hben35096 @zhaoxi12312 @ioritree @Winson0616 @q7793527 @wushengda @AiD-teng @liuweikaiphoto @curtis110101010 @ouyang3333 @sdjkdghj123 @chengyinqiao1976 最新版 修复了双击搜索, 大家试试

**Comment by edensgate** [comment]
> 开始出现搜索卡顿的版本是12月10日开始的，也就是哈希值： [0ed6982](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/commit/0ed6982f23d225dac56fb4dbd4407998cb89d056) 大家可以回退到 12月2日，即哈希值：cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a
> 
> 或者删除 MenuTranslate.js 文件中的这一行的`, true` ![PixPin_2024-12-19_01-13-51](https://private-user-images.githubusercontent.com/139383150/397034424-097d288d-0ffa-410c-b1cb-a0004df7028e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjE5MzAsIm5iZiI6MTczNTEyMTYzMCwicGF0aCI6Ii8xMzkzODMxNTAvMzk3MDM0NDI0LTA5N2QyODhkLTBmZmEtNDEwYy1iMWNiLWEwMDA0ZGY3MDI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMDEzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmRiOGMzYmNjNjAwNGY5YWQ1ZjE1NDc0NmFkYzE2ZTczMDVmOGEyM2E4YjA3MzU3YTFhNmEwNjliMmMzZDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9V9qxeO6HOyo1bC48N0VqmlLhyzxXpnSA8mVm3df-PE)

大佬🐂🍺

**Comment by KarryCharon** [comment]
> > 开始出现搜索卡顿的版本是12月10日开始的，也就是哈希值： [0ed6982](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/commit/0ed6982f23d225dac56fb4dbd4407998cb89d056) 大家可以回退到 12月2日，即哈希值：cf8f9a848e183d8a3f5892afe6a6c5f09767cb2a
> > 或者删除 MenuTranslate.js 文件中的这一行的`, true` ![PixPin_2024-12-19_01-13-51](https://private-user-images.githubusercontent.com/139383150/397034424-097d288d-0ffa-410c-b1cb-a0004df7028e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjE5MzAsIm5iZiI6MTczNTEyMTYzMCwicGF0aCI6Ii8xMzkzODMxNTAvMzk3MDM0NDI0LTA5N2QyODhkLTBmZmEtNDEwYy1iMWNiLWEwMDA0ZGY3MDI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMDEzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmRiOGMzYmNjNjAwNGY5YWQ1ZjE1NDc0NmFkYzE2ZTczMDVmOGEyM2E4YjA3MzU3YTFhNmEwNjliMmMzZDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9V9qxeO6HOyo1bC48N0VqmlLhyzxXpnSA8mVm3df-PE)
> 
> 大佬🐂🍺

最新版应该修复了啊 https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/commit/0b9dea2cd07b177a64941ab76ceda1cb77eca5bb

**Comment by DIERWU** [comment]
禁止AIGODLIKE-ComfyUI-翻译
