### ISSUE TITLE
【功能】是否可以增加中间缓存文件，来保留用户自定义的节点名称

### ISSUE THREAD

**Issue by youyegit** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#35]
这是我的思路，不知道是否方便实现。
1、增加一个按钮，选择是否保留自定义节点名称。
2、如果选择保留自定义节点名称，程序先读取加载的工作流文件，保留自定义节点名称的记录缓存文件。
3、然后切换语言时，最后用自定义节点名称的记录缓存文件覆盖。

感谢作者提供的插件！

**Comment by Yorha4D** [comment]
@youyegit 目前对于翻译要兼容多国语言，所以必须得使用节点原本的名称，即使它已经被加了别名。但我觉得之后可以添加更细致的开关，让你决定是否对某个部分进行翻译替换
