### ISSUE TITLE
全部大写的命名也是够炸裂的

### ISSUE THREAD

**Issue by shawnwu2022** [AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION#36]
大写的----------服

**Comment by Yorha4D** [comment]
@shawnwu2022 HI~没必要代入极端的负面情绪，这并不能解决任何问题。既然你已经看到了问题，就应该去想办法改进。
低端的行为只会使得别人认为你是一个什么都做不到，只会无能狂怒的孩子
共勉，以上
