### ISSUE TITLE
装了翻译节点后，右键菜单无法弹出，节点下拉框也无法下拉。

### ISSUE THREAD

**Issue by DreamLoveBetty** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#39]
装了翻译节点后，右键菜单无法弹出，节点下拉框也无法下拉。
系统：win11,python3.10.11,comfyui官方一键包。

**Comment by Yorha4D** [comment]
@DreamLoveBetty 有截图或者报错信息之类的么，我刚更新了最新的COMFYUI它一切正常
