### ISSUE TITLE
更新后，插件失效了？

### ISSUE THREAD

**Issue by hben35096** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#53]
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/139383150/31dbf1f2-0bc9-4269-8389-91d18321d6e7)
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/139383150/ee1e4d50-ddb0-45d5-ba62-02aa88b7ac8d)

这个最新版本失效了，我回退到：
65d938fdc0aeadb4857289721474237e37b50b95
它才正常工作。

**Comment by Yorha4D** [comment]
@hben35096 可能是否词合并多了符号，正在修复
