### ISSUE TITLE
按照说明进行了安装，但没有起效果

### ISSUE THREAD

**Issue by github-mes** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#57]
更新了主体，更新了管理器，来来回回重装了好机会插件，但依然没有效果，设置框中并没有出现语言选项
![01](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/82822863/68d0bf49-3458-4c31-9144-7f6e9977e678)

**Comment by Yorha4D** [comment]
@github-mes 这个信息里没有关于翻译工具的报错信息，或许你应该给到从启动到停止的完整报错信息

**Comment by github-mes** [comment]
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/82822863/a72e72c3-7f2a-4357-874d-99bd164fc936)
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/82822863/0caf0ca4-76bc-464e-9435-1facd665e42d)

**Comment by Yorha4D** [comment]
@github-mes 删除个文件后重开看看
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/116185401/7c4743ca-9076-4149-866d-b281545423ae)

**Comment by tiwentichat** [comment]
> @github-mes 删除个文件后重开看看 ![image](https://user-images.githubusercontent.com/116185401/270331044-7c4743ca-9076-4149-866d-b281545423ae.png)

我也遇到了同样问题。图中的文件夹删除重开后又出现了。
comfyui 是githubrepo里下载的最新版本。

**Comment by Yorha4D** [comment]
@tiwentichat extension有这个文件夹没问题，主要是现在comfyui是否可以用了？可以尝试着升级下comfyui
