### ISSUE TITLE
ComfyUi_PromptStylers

### ISSUE THREAD

**Issue by luci188** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#58]
大神，你好
这个插件现在使用的人很多烦请更新一下~
感谢~

**Comment by Yorha4D** [comment]
@luci188 地址发一下

**Comment by DorotaLuna** [comment]
这个的内容和[sdxl_prompt_styler](https://github.com/twri/sdxl_prompt_styler)是一样的，只是他重命名了一遍。

**Comment by Yorha4D** [comment]
YEEES...
