### ISSUE TITLE
issue: category error

### ISSUE THREAD

**Issue by ltdrdata** [AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION#6]
![en](https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION/assets/128333288/d5c4bfd7-31af-4031-a183-97d704f61ed9)
![kr](https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION/assets/128333288/76cd3a2e-1f87-47a2-bb39-253b08c6e9b6)

When applying the locale, there's an issue where the categories don't appear consistently and get distorted.

**Comment by KarryCharon** [comment]
fixed now!
