### ISSUE TITLE
请求翻译

### ISSUE THREAD

**Issue by liulsg** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#60]
请求翻译蒙版遮罩插件。
https://github.com/BadCafeCode/masquerade-nodes-comfyui
请求翻译（里面好几个颜色提取器节点，对于latent的噪点混合作用极大）
https://github.com/melMass/comfy_mtb/commit/90aee83797a863cf4797cdbe187f949061cbd176

**Comment by Yorha4D** [comment]
@liulsg 我先看看

**Comment by DorotaLuna** [comment]
更新了masquerade-nodes
#63
