### ISSUE TITLE
ZH_TW

### ISSUE THREAD

**Issue by KumaPlayWithShader** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#65]
https://drive.google.com/file/d/1oJHovhXlpC9z2tXmqkwox72G_WGlyG5O/view?usp=sharing

**Comment by Yorha4D** [comment]
@KumaPlayWithShader Received, I will complete the merger as soon as possible

**Comment by Yorha4D** [comment]
@KumaPlayWithShader 我留意到很多是直接进行的简体中文转换繁体中文，这些在繁体使用者中是否会出现一些比如像圆珠笔和原子笔这样的词汇差异？

**Comment by ytchen175** [comment]
@KumaPlayWithShader I saw it accidently, and as a native speaker, I just finished the translation of TC manually and send a PR to @Yorha4D, thanks for your files!

**Comment by Yorha4D** [comment]
> @KumaPlayWithShader I saw it accidently, and as a native speaker, I just finished the translation of TC manually and send a PR to @Yorha4D, thanks for your files!我偶然看到了它，作为母语人士，我刚刚手动完成了TC的翻译并发送了PR，感谢您的文件！

@ytchen175 Received, after completing the usability test, the code will be merged (expected to take 1-2 days)
