### ISSUE TITLE
安装后进入comfyui在设置中没有插件相关内容

### ISSUE THREAD

**Issue by Xian1yu2jun3** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#72]
我在按照说明安装后用说明中的方法无法找到插件，我看到很多人都有这个问题，我尝试更换浏览器，重新安装，把所有插件删除只装您的插件依然有这个问题。
![1b58d606b0ddddc5b0b8593a444c813](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/127582987/71b7e15c-91d0-415c-8a10-1c3ea09511ca)
![d6414e5bab8c2a0272bda2614d55f99](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/127582987/07ec45dc-55ec-45b6-873f-ee09d3a19639)

**Comment by BitToNet** [comment]
还真是，在移动硬盘里面不行
