### ISSUE TITLE
在节点右键切换为输入时，会有严重延迟和意外情况

### ISSUE THREAD

**Issue by hben35096** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#86]
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/139383150/2337d1d3-10d7-493a-8e05-4123a8b62d90)
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/139383150/a610cff0-fd9f-430d-9bf7-63ac0a204784)

我不知道怎么发视频，情况是这样的：
ComfyUI版本：b935bea3a0201221eca7b0337bc60a329871300a
AIGODLIKE-COMFYUI-TRANSLATION：18e1079c6d872c8f4aa0706e2f1f7ccc7223df46
如果是在英文、韩语模式下，右键把节点中的组件、选项转为输入接口，是很快速的，转换也不会有什么问题；
切换为中文、繁体中文、日语等模式之后，切换为输入接口会有严重延迟，出现如上图的情况。有时要刷新页面才能正常显示，有时因为延迟，多点了几下菜单，就变成了多个输入接口了，刷新也不会恢复正常。

我想这应该是插件的问题，因为英语和韩语都是正常的，也只是一个小问题。

**Comment by KarryCharon** [comment]
@hben35096 已修复, 感谢反馈

**Comment by hben35096** [comment]
> 已修复， 感谢反馈
万分感谢，刚测试了不同语言，都没有问题，非常流畅~
