### ISSUE TITLE
设置里面没有语言选项

### ISSUE THREAD

**Issue by C-Kristal** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#98]
菜单设置里面，找不到可以设置语言的选项。

**Comment by maxadc** [comment]
同样的问题
ComfyUI_windows_portable_nvidia_cu121_or_cpu_28_10_2023 
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/23376041/6a29c922-fe3d-4e8b-8036-3b9d02b2947f)
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/23376041/4ce6d51f-4921-4fde-8108-b3b7796d29b7)

**Comment by dljscholar** [comment]
我的也是  怎么解决 这个问题呢

**Comment by Yorha4D** [comment]
检查下浏览器看看

**Comment by maxadc** [comment]
> 检查下浏览器看看

控制台？没发现问题。浏览器也换过了！

**Comment by dljscholar** [comment]
搞了很久还是没有解决 怎么办 是不是系统版本的原因呢

**Comment by Yorha4D** [comment]
或许可以来QQ群艾特下辣椒，远程看看，理论上不应该会有这个问题

**Comment by dljscholar** [comment]
这个问题 我今天搞定了  首先把浏览器的缓存清理掉 然后把浏览器重置一下 即可

**Comment by maxadc** [comment]
@Yorha4D 找到方法。你的教程写得不对！你的教程中写的是 放到 ComfyUI\custom_nodes\下 而实际上，貌似需要放到web/extensions下。我看了控制台错误，复制了一份 到web/extensions 下这才解决。

**Comment by Yorha4D** [comment]
@Yorha4D 是需要放到ComfyUI\custom_nodes\下，然后自动运行会在web/extensions设置文件映射，但你的不知道什么原因没有创建成功

**Comment by DahuX** [comment]
> @Yorha4D 是需要放到ComfyUI\custom_nodes\下，然后自动运行会在web/extensions设置文件映射，但你的不知道什么原因没有创建成功

问题应该就在设置文件映射这里。非 NTFS 格式的存储设备上（ 比如另一种常见的 exFAT ）并不支持设置文件映射（Symbolic Link），所以按流程正常安装后，设置里依然不会生效

**Comment by dlinliner** [comment]
哎，同样的问题，重置了浏览器，web/extensions里面也有映射文件夹，manage里面显示安装成功，但设置菜单里就是没有language
