### ISSUE TITLE
在某些电脑下不起效果

### ISSUE THREAD

**Issue by uoooooou** [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#99]
![f1014e0a396f90f160ad686f159c33b](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/151850369/36a4f494-eeb4-4a09-ad8c-0a98196fe48e)

命令行里提示函数不正确

**Comment by Yorha4D** [comment]
1使用较新内核的浏览器比如edge和谷歌
2迁移给其他人使用注意清除下web/extensions的缓存文件夹
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/assets/116185401/98d6df48-474d-45ef-bb03-502f122ccdec)
